/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horarios;

import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeListenerProxy;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ander
 */
public class calendario extends javax.swing.JFrame {

    /**
     * Creates new form calendario
     */
    Coneccion cc;
    Connection cn;
    String cedDoc;
  
    public calendario(String ced) {
        initComponents();
        cc = new Coneccion();
        cn = cc.conectar();
        cedDoc=ced;
        dato= calendario.getDate();
        SimpleDateFormat formateador2 = new SimpleDateFormat("dd-MM-yyyy");
        String fec = formateador2.format(dato);
        cargarDatosTabla(fec);
        colorear();
        
        calendario.getDayChooser().addPropertyChangeListener("day",new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
     

//To change body of generated methods, choose Tools | Templates.
         dato= calendario.getDate();
        SimpleDateFormat formateador2 = new SimpleDateFormat("dd-MM-yyyy");
        String fec = formateador2.format(dato);
        //System.out.println(fec);
        cargarDatosTabla(fec);
                
            
            }
        });
    }
    public calendario() {
        initComponents();
        cc = new Coneccion();
        cn = cc.conectar();
        cedDoc="1805037619";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendario = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecordatorio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioMouseClicked(evt);
            }
        });

        tblRecordatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRecordatorio);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("RECORDATORIOS");

        jButton1.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(151, 151, 151))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void pintar(String fecha) {
        if (calendario.getYearChooser().getYear() == Integer.valueOf(fecha.substring(6, 10))) {
            if (calendario.getMonthChooser().getMonth() + 1 == Integer.valueOf(fecha.substring(3, 5))) {
                int sa = 0;
                for (int s = 7; s < 14; s++) {
                    if (calendario.getDayChooser().getDayPanel().getComponent(s).isVisible() == false) {
                        sa = sa + 1;
                    }
                }
                calendario.getDayChooser().getDayPanel().getComponent(Integer.valueOf(fecha.substring(0, 2)) + sa + 6).setBackground(Color.BLUE);
            }
        }
    }


    public void colorear() {
        ArrayList<String> f = new ArrayList<String>();
//        conexion cc = new conexion();
//        Connection cn = cc.conectar();
//        System.out.println(txtUsuario.getText());
        String sql = "SELECT fec_rec FROM recordatorios WHERE ced_doc_per='" + cedDoc + "'";
        calendario.setSundayForeground(Color.RED);
        calendario.setDecorationBackgroundColor(Color.yellow);
        calendario.setDecorationBackgroundVisible(true);
        calendario.getDayChooser().getDayPanel().getComponent(5).setBackground(Color.BLUE);
        Statement ps;
        try {
            ps = cn.createStatement();
            ResultSet rs = ps.executeQuery(sql);
            while (rs.next()) {
                f.add(rs.getString(1));
            }
            for (int i = 0; i < f.size(); i++) {
               // pintar(f.get(i));
            }
        } catch (SQLException ex) {
            //Logger.getLogger(PrincipalAlarma.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }
    
    
    Date dato;
    private void calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_calendarioMouseClicked
DefaultTableModel modeloTabla;
    public void cargarDatosTabla(String fecha) {
        String titulos[] = {"ID","FECHA", "HORA", "DESCRIPCIÓN"};
        modeloTabla = new DefaultTableModel(null, titulos) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblRecordatorio.setModel(modeloTabla);
        tblRecordatorio.getTableHeader().setReorderingAllowed(false);

        

        String sql = "select * from recordatorios where ced_doc_per='" + cedDoc + "' "
                + "AND fec_rec= '"+fecha+"'"
                + " order by fec_rec asc";
        System.out.println(sql);
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            String fila[] = new String[4];
            while (rs.next()) {
                fila[0] = rs.getString("id_rec");
                fila[1] = rs.getString("fec_rec");
                fila[2] = rs.getString("hor_rec");
                fila[3] = rs.getString("des_rec");
                modeloTabla.addRow(fila);
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de base: " + ex);
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRecordatorio;
    // End of variables declaration//GEN-END:variables
}
